### ISSUE TITLE
OpenTerrainGenerator 1.12.2 v9_r10 doesn't work with Streams

### ISSUE THREAD

**Issue by PG85** [delvr/Streams#109] opened 2020-09-04 02:18 UTC
For the latest dev versions of OTG 1.12.2 v9, Streams doesn't work anymore. Some classes were moved (com.pg85.otg.forge.ForgeWorld -> com.pg85.otg.forge.world.ForgeWorld), I created a workaround so Streams' old implementation should still work, that fixed any crashes/exceptions but Streams still only worked for vanilla worlds. I didn't see any more exceptions, so I'm not sure what broke Streams. Will need some help with this, could you try building with the latest dev version of OTG and see if that shows any problems? Jar is attached (rename .zip to .jar), code is here: https://github.com/PG85/OpenTerrainGenerator/tree/1.12-v9) .

*I've not included the fixes/workaround for the ForgeWorld refactor, so you'll get build errors. OTG v9 should be released within a few weeks, so if you could do an update some time after that, that would be ideal. Big thanks and cheers.

[OpenTerrainGenerator-1.12.2 - v9.0_r11.zip](https://github.com/delvr/Streams/files/5172283/OpenTerrainGenerator-1.12.2.-.v9.0_r11.zip)

**Comment by PG85** [comment] 2020-09-04 02:26
https://github.com/PG85/OpenTerrainGenerator/issues/515

**Comment by delvr** [comment] 2020-10-27 00:09
Hi @PG85, this should be fixed in the new Farseek 2.5.1. Could you give it a try and let me know if it works? Thanks!

**Comment by PG85** [comment] 2020-10-27 02:04
![2020-10-27_03 03 13](https://user-images.githubusercontent.com/6781444/97247970-02722100-1801-11eb-9525-e47403fe778b.png)
![2020-10-27_01 53 59](https://user-images.githubusercontent.com/6781444/97247985-08680200-1801-11eb-8468-f4ec068ec5e1.png)

Looking good, big thanks :)

*There do appear to be some lines going across the streams, not sure if that's intentional? Looks like it happens every time there's an elevation change in the water.

**Comment by PG85** [comment] 2020-10-27 02:13
![2020-10-27_03 13 17](https://user-images.githubusercontent.com/6781444/97248574-5fbaa200-1802-11eb-9c9d-4551b19d94a0.png)

**Comment by delvr** [comment] 2020-10-27 06:58
Glad to hear it's working. Yeah those solid lines are an old bug I've been unable to fix so far, they're normally quite rare though. Do they happen for every elevation change in all streams for the new OTG? Are other mods present in your test?

In any case I'll take another look this week and see if I have more luck finding the cause.

**Comment by PG85** [comment] 2020-10-27 09:26
![2020-10-27_10 22 18](https://user-images.githubusercontent.com/6781444/97281939-60712980-183e-11eb-8342-a91af75877db.png)
![2020-10-27_10 22 15](https://user-images.githubusercontent.com/6781444/97281945-636c1a00-183e-11eb-8bbf-451b9f98b1ca.png)
![2020-10-27_10 21 58](https://user-images.githubusercontent.com/6781444/97281971-6d8e1880-183e-11eb-90a2-aee765976d21.png)

They do seem to appear quite consistently, I'm seeing them often. It looks like it's only happening when the elevation change actually switches to the next layer of blocks above/below. So it looks like just one "transition block" at the end that's missing. Thanks and cheers.

*Only have some minor QOL mods btw:

![afbeelding](https://user-images.githubusercontent.com/6781444/97282661-3b30eb00-183f-11eb-8043-7e224d5e9a82.png)

**Comment by DieselpunkCyborg** [comment] 2020-11-01 05:12
Sorry if this is off-topic, but which version of OTG does Streams work with? I went back to v8.3 and I'm still getting the transition blocks.

I just want to increase terrain height to get more Streams, this mod is gorgeous.

**Comment by delvr** [comment] 2020-11-12 05:28
@PG85 @DieselpunkCyborg The new Streams 0.4.9 should fix the stone "bridges" over streams, could you give it a try?

**Comment by PG85** [comment] 2020-11-12 06:34
![2020-11-12_07 24 11](https://user-images.githubusercontent.com/6781444/98904108-49c30780-24b9-11eb-8b0c-2af2c3bde9f6.png)
![2020-11-12_07 24 00](https://user-images.githubusercontent.com/6781444/98904140-5fd0c800-24b9-11eb-87b2-7dd36b99d084.png)
Yep, looking good! Big thanks :)

**Comment by delvr** [comment] 2020-11-12 20:17
Glad to hear it! 👍

**Closed as completed by delvr** 2020-11-12 20:17 UTC
Labels: compatibility
