### ISSUE TITLE
Crash server 1.12.2

### ISSUE THREAD

**Issue by SeagalKru** [delvr/Streams#90] opened 2019-09-07 22:44 UTC
[crash-2019-09-08_00.19.55-server.txt](https://github.com/delvr/Streams/files/3587111/crash-2019-09-08_00.19.55-server.txt)

**Comment by Vagor96** [comment] 2019-11-19 00:43
Looks like #74 
And this is a dupe of delvr/Farseek#51

**Comment by delvr** [comment] 2019-11-26 05:16
Thanks Vagor96, please see the linked issues for updates. Closing as duplicate.

**Closed as completed by delvr** 2019-11-26 05:16 UTC
Labels: duplicate
