### ISSUE TITLE
Crash on Startup 1.10.2

### ISSUE THREAD

**Issue by Drakoflame** [delvr/Streams#31] opened 2016-12-20 19:06 UTC
http://pastebin.com/6c9rgJFV Not entirely sure, if someone could help me out, I'd really love to have streams in my worlds!

**Comment by delvr** [comment] 2016-12-20 19:48
Thanks for reporting, seems to be a duplicate of https://github.com/delvr/Streams/issues/27 which I'm looking into.

**Closed as completed by delvr** 2016-12-20 19:48 UTC
Labels: duplicate, 1.9.4/1.10
