### ISSUE TITLE
More Customizable Soil Fall

### ISSUE THREAD

**Issue by Amaxter** [delvr/Streams#6] opened 2015-09-14 02:15 UTC
Could we possibly be able to disable certain soil blocks (like Aether Grass :P) in the future within the config?

**Comment by delvr** [comment] 2015-12-31 03:13
Duplicate of [Repose issue #2](https://github.com/delvr/Repose/issues/2) which is being worked on for a future version of that mod.

**Closed by delvr** 2015-12-31 03:13 UTC
