### ISSUE TITLE
Server Crash/Freez: related to Streams

### ISSUE THREAD

**Issue by SirAron111** [delvr/Streams#83] opened 2019-07-27 12:00 UTC
Server Crash/Freez: related to Streams
I don’t know what’s causing it to Freez and Crash but the log spams around Stream erroring messages.
https://pastebin.com/QFa96NxD

Streams-1.12-0.4.7.jar
Forge 14.23.5.2838

**Comment by Vagor96** [comment] 2019-07-27 12:32
This could be related to #74 
Which mods do you use?

**Comment by SirAron111** [comment] 2019-07-27 15:22
The complet mod list can be found here on the very bottom https://www.curseforge.com/minecraft/modpacks/dimension-zero a user reported this crash issue

**Comment by dkambersky** [comment] 2019-08-29 16:05
Looks like a dupe of #74.

**Comment by Vagor96** [comment] 2019-11-19 00:48
Does the issue persist if you remove AutoRegLib?

**Comment by delvr** [comment] 2019-11-26 05:18
Please see #74 for updates. Closing as duplicate.

**Closed as completed by delvr** 2019-11-26 05:18 UTC
Labels: duplicate
